### ISSUE TITLE
Error while creating Spectra object : undefined columns selected

### ISSUE THREAD

**Issue by RosarioI** [bryanhanson/ChemoSpec#11]
I am trying to create a spectral object with function files2SpectraObject. I have 1715 files (49 groups with 35 elements each). I named the files according to the vignette. Eah file is .csv and has just 2 columns. The first column contains the frequency and the second the intensity. When I run the function, the following error is returned:
files2SpectraObject is checking the first file

files2SpectraObject will now import your files
Importing file:  GEN1_R1_1.csv 
Error in `[.data.frame`(temp, , 2) : undefined columns selected

The function I run was:

files2SpectraObject(gr.crit = c("GEN1_R1_", "GEN2_R1_", "GEN3_R1_","GEN4_R1_","GEN5_R1_","GEN6_R1_","GEN7_R1_","GEN8_R1_","GEN9_R1_","GEN10_R1_","GEN11_R1_","GEN12_R1_","GEN13_R1_","GEN14_R1_","GEN15_R1_","GEN16_R1_","GEN17_R1_","GEN18_R1_","GEN19_R1_","GEN20_R1_","GEN21_R1_","GEN22_R1_","GEN23_R1_","GEN24_R1_","GEN25_R1_","GEN26_R1_","GEN27_R1_","GEN28_R1_","GEN29_R1_","GEN30_R1_","GEN31_R1_","GEN32_R1_","GEN33_R1_","GEN34_R1_","GEN35_R1_","GEN36_R1_","GEN37_R1_","GEN38_R1_","GEN39_R1_","GEN40_R1_","GEN41_R1_","GEN42_R1_","GEN43_R1_","GEN44_R1_","GEN45_R1_","GEN46_R1_","GEN47_R1_","GEN48_R1_","GEN49_R1_"), fileExt = "\\.(csv)$", gr.cols = c("red3", "dodgerblue4"), freq.unit = "1/CM", int.unit = "abs", descrip = "Spectra of two genotypes of Miscanthus", out.file = "ABR33 Rep1 ", debug = T)

Any suggestion?

Thanks in advance,
Rosario

**Comment by RosarioI** [comment]
Just solved the issue by adding sep= "," to the above function

**Comment by bryanhanson** [comment]
Super!  You now have to specify a few things about your input files, this gives a lot more flexibility.  I was finding that "csv" files from various instruments and countries were not really all that consistent.  So the new version can handle anything.
