### ISSUE TITLE
baselineSpectra: replacement has 3 rows, data has 2

### ISSUE THREAD

**Issue by rvernica** [bryanhanson/ChemoSpec#13]
When using `baselineSpectra`, changing the algorithm and the arguments in the *Baseline correction* window triggers errors. Here are the steps:

1. Start interactive baseline correction:
      ```R
      > data(SrE.IR)
      > baselineSpectra(SrE.IR)
      ```
1. Update algorithm and parameters:
   * Select *Asymmetric Least Squares (als)*:
        ```R
        Error in unclass(x) : cannot unclass an external pointer`
        ```
   * Change *Main smoothing (lambda2)* from `8` to `6`:
        ```R
        Error in `$<-.data.frame`(`*tmp*`, "current", value = c(5, 6.3, 0.05)) : 
          replacement has 3 rows, data has 2
        ```
    * Click *Update plot*. The following plot is generated:
![err](https://user-images.githubusercontent.com/241185/28945654-3286e044-785c-11e7-92cb-f1b8f989e105.png)
---
```R
> sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: Fedora 24 (Workstation Edition)

Matrix products: default
BLAS/LAPACK: /usr/lib64/R/lib/libRblas.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] gWidgetsRGtk2_0.0-84 cairoDevice_2.24     gWidgets_0.0-54      RGtk2_2.20.33        ChemoSpec_4.4.85    

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.12       scidb_2.0.0        bit_1.1-12         munsell_0.4.3      colorspace_1.3-2   rlang_0.1.1        plyr_1.8.4         tools_3.4.1        js_1.1            
[10] grid_3.4.1         baseline_1.2-1     data.table_1.10.4  gtable_0.2.0       R.oo_1.21.0        openssl_0.9.6      bit64_0.9-7        lazyeval_0.2.0     digest_0.6.12     
[19] tibble_1.3.3       RColorBrewer_1.1-2 ggplot2_2.2.1      R.utils_2.5.0      curl_2.8.1         V8_1.5             compiler_3.4.1     scales_0.4.1       R.methodsS3_1.7.1 
[28] SparseM_1.77       jsonlite_1.5      
```

**Comment by bryanhanson** [comment]
On a Mac, if I do `baselineSpectra(SrE.IR)` with no method specified, I cannot reproduce what you see as something is not compatible in the GTK toolchain I have and R 3.5 RC, so I get a lengthy error about GTK functions (not surprising).

However, this:

```
test <- baselineSpectra(SrE.IR, method = "xyz")
```
works for all values of method documented in package `baseline` except for `shirley`.

**Comment by rvernica** [comment]
I see. It might be some GTK issue. That works for me as well, but this didn't:
```R
> baselineSpectra(SrE.IR, method="als", lambda = 6)
Error in baseline::baselineGUI(dat, ...) : unused argument (lambda = 6)
```

**Comment by bryanhanson** [comment]
Good observation.  Use `int = FALSE` to make it accept `lambda`.  This issue arises because the `baselineGUI` function in `baseline` does not have the `...` argument to pass extra arguments along to the underlying method (maybe these extra arguments show up in a dialog box for some systems, but not on mine.  I just get a static two panel plot).  I will file an issue on this with them if I can find an issue tracker.

**Comment by bryanhanson** [comment]
`baseline` has not been updated for 2 years and doesn't not have a public repo or issue tracker, so I wrote to the maintainer directly.

Since you have a working GTK set up (I think), try `baselineSpectra(SrE.IR, method = "als")` and see if a dialog box appears which gives you the ability to change extra arguments like `lambda`.  Based on the not quite working behavior I see, that may be the intent.

**Comment by bryanhanson** [comment]
Just looked at their code for `baselineGUI` and I'm pretty sure they intend for buttons, sliders and other goodies to appear, but it would take an hour to look through all of it, so perhaps the test suggested above may answer it faster.

**Comment by rvernica** [comment]
Yes, I do have a working GTK setup, the dialog appears, and I can change the parameters successfully.

I think the root problem is with the `baselineGUI` window. When a different algorithm is selected, the window is not updated to reflect the parameters of the selected algorithm. For example, for the steps that I reported initially, there is no `lambda2` parameter for the `als` algorithm. So, when I adjust that parameter things go haywire.

**Comment by bryanhanson** [comment]
Alright, that's good to know.  If I hear from the author/maintainer, I'll pass this along.

**Comment by rvernica** [comment]
Thanks for looking into these issues.

**Comment by bryanhanson** [comment]
I heard back from the author of `baseline` and there is a way to customize the GUI that I had not noticed.  This may be the solution, I'm not certain.  I'm going to keep this issue open for now, as I don't have time to address it probably until the end of the year (academic year just getting going here!).
