### ISSUE TITLE
Not possible to create Spectra object from CSV file

### ISSUE THREAD

**Issue by adminRHT** [bryanhanson/ChemoSpec#14]
Hello,

I have a single file "spectrum.xy" with the content as follows:

[ INIT OF FILE ]
freq,data
-244.378,3281.62
-241.835,-5469.72
-239.293,1090.93
-236.751,2729.67
and more pair of values...
[ END OF FILE ]

I am not able to load these data into an Spectra object. Either using file2SpectraObject nor matrix2SpectraObject,

However I can read easily this file with read.csv function (package readr)

Could you please show me an example of how do I have to call the function? Is the file format wrong??

> spec <- matrix2SpectraObject(gr.crit = "spectrum",  freq.unit = "no frequency unit provided",
 int.unit = "no intensity unit provided", descrip = "test import", in.file="spectrum.xy")
**Error in spectra$data[i, ] : subscript out of bounds
In addition: Warning message:
In groupNcolor(spectra, gr.crit, gr.cols) :
  There was no match for gr.crit value spectrum among the file names.**

Changing the extension to csv does not change anything.

Thanks in advance,
Tay

**Comment by bryanhanson** [comment]
Hi Tay... Make sure your ChemoSpec is up to date (should be 4.4.97), just on principle, but I think your problem is you need to add `sep = ","` to your call.  That's documented in the `...` argument of either import function.  `files2SpectraObject` should have given you a bit of guidance (if you are on a recent version) as to this error, but `matrix2SpectraObject` is not yet that smart.  If this doesn't make things work, I see a possible cause in `matrix2SpectraObject` when there is only 1 spectrum, I don't think it's a problem in `files2SpectraObject` but I may need to test.  Let me know.

**Comment by adminRHT** [comment]
Version is ok, 4.4.97
I added sep and header arguments. This time the error is different:

```
spec <- files2SpectraObject(gr.crit = "spectrum", sep = ",", freq.unit = "no frequency unit provided",int.unit = "no intensity unit provided",  descrip = "test import", fileExt = ".xy", header=TRUE, dec=".")
*** There seem to be one or more problems with these spectra!

Error message from R: Sorry, we can't continue this way: It's not me, it's you!

There was a problem importing your files!

Are you importing csv or similar files?
Did you get a message such as 'undefined columns selected'?
You probably need to specify sep, header and dec values
Please read ?files2SpectraObject for details

For any trouble importing files set debug = TRUE

Warning messages:
1: In groupNcolor(spectra, gr.crit, gr.cols) :
  At least one file name did not correspond any entry in gr.crit and its group is thus NA
2: In chkSpectra(spectra) :
  The dimensions don't make sense (colors, symbols)
```

**Comment by adminRHT** [comment]
Yes, you are right. I got an error that is already fixed. The problem comes because I have other file in the same directory with other format (name of the file different and different separator). So I had to repeat the call to the function but with only one file in the directory.

Thanks again Bryan!
