### ISSUE TITLE
makeEllipsoid: 95% Confidence ellipsoid of data instead of mean

### ISSUE THREAD

**Issue by mluerig** [bryanhanson/ChemoSpec#15]
Hi Bryan,
don't know if this is right place to ask - this is not really an issue, but since it's part of the package (and it is not mentioned until further down in the description) I figured I would ask anyway if this modification in your opinion returns the 95% confidence interval **ellipsoid for the data itself**, instead of the mean:

ell.95<-function (data, cl = 0.95) {
  
npoints <- 1000
mean <- colMeans(data)
p <- length(mean)
n <- nrow(data)

sphere <- matrix(rnorm(npoints * p), ncol = p)
cntr <- t(apply(sphere, 1, normVec))

cov <- var(data)
ev <- eigen(cov)
cntr <- cntr %*% diag(sqrt(ev$values)) %*% t(ev$vectors)
Fcrit <- qf(cl, p, n - p)

cntr <- cntr * Fcrit

colnames(cntr) <- colnames(data)
cntr + rep(mean, each = npoints)

**Comment by bryanhanson** [comment]
Hmm... I'm not sure I understand what you are asking: the code you began with computes the ellipse using the data... how could it be any other way?  I'm also a bit confused about the function you shared.  The only difference I can see from the original is in how `cntr` is computed, which is different by a scale factor.  Am I missing something?
