### ISSUE TITLE
 import files in Chemospec doesn't work

### ISSUE THREAD

**Issue by LuisCanoA** [bryanhanson/ChemoSpec#16]
Hi! I try to import files in ChemoSpec, I have a collection of 15 samples (all have the A1... A15) for import.... 

`glio <- files2SpectraObject(gr.crit=c("A"),
                         gr.cols = c("auto"), freq.unit = "ppm",
                           int.unit = "peak intensity",descrip = "glios",
                           out.file = "glios",sep=",", dec = ".", debug = T,
                         fileExt = ".csv")`

and I have this error: 

Error message from R: number of items to replace is not a multiple of replacement length

There was a problem importing your files!

Are you importing csv or similar files?
Did you get a message such as 'undefined columns selected'?
You probably need to specify sep, header and dec values
Please read ?files2SpectraObject for details

For any trouble importing files set debug = TRUE

I changed the  format of CSV file, but I always have the same result. 
somebody have a idea for fix it ?

**Comment by bryanhanson** [comment]
Yes, this error almost always occurs because some of your spectra have different numbers of entries (meaning different numbers of frequency values).  Open your csv files and check how many rows you see in each.  At least one of them differs from the others.  You’ll have to remove the shorter/longer data files in order to import the rest.

Let me know how it goes.

**Comment by LuisCanoA** [comment]
I followed your advice and .... it works now !!!! 
Thank your Master !

**Comment by bryanhanson** [comment]
Just let me know any other issues/questions!

**Comment by LuisCanoA** [comment]
Hi again, now I have this issue:

` mamaBaseLinePcaRobust <- r_pcaSpectra(mamaBaseLine, choice = "noscale")
Error in r_pcaSpectra(mamaBaseLine, choice = "noscale") : 
  You need to install package pcaPP to use this function`

them... I installed the pcaPP package...

I've received that error: 
`Error: x$k <= ncol(x$x) is not TRUE`

I didn't have problems with the c_pcaSpectra function ... but for robust ... I don't know what happens ?

**Comment by bryanhanson** [comment]
The example in `?r_pcaSpectra` works fine for me with ChemoSpec 4.4.97 and R 3.4.4  Perhaps check that you have the current versions of each, and re-launch R and try again.

For the sake of organization (one problem per Github issue) I'm going to close this issue.  Feel free to write me directly at hanson@depauw.edu for what seem to be small problems, and if you think it might be a larger issue you can  open a new Github issue ticket.  That's just a guide, feel free to ask by whatever means works best!
