### ISSUE TITLE
Error in files2SpectraObject - S4 object?

### ISSUE THREAD

**Issue by spriour** [bryanhanson/ChemoSpec#17]
Hi there,
I am new with ChemoSpec, and I am trying to analyse some FTIR data. I got an error from the begining with files2SpectraObject
` files2SpectraObject(gr.crit = c("p", "m"), gr.cols = c("red", "blue"), freq.unit = "cm^-1", int.unit = "peak intensity", descrip = "Mixture DoE blanks and probiotics", out.file = "MixtrureIR", header = FALSE, sep=",", dec=".", debug="TRUE")`

The files are imported, but I am getting this error:

> Error message from R: trying to get slot "nir" from an object (class "Spectra") that is not an S4 object 
> There was a problem importing your files!
> Are you importing csv or similar files?
> Did you get a message such as 'undefined columns selected'?
> You probably need to specify sep, header and dec values
> Please read ?files2SpectraObject for details
> For any trouble importing files set debug = TRUE

I am still beginer-ish with R, so I am not exactly sure what is a S4 object, and how to correct this error...

Thanks!

**Comment by bryanhanson** [comment]
Hmmm... Your function call looks fine, and I gather from the fact that you say the files are imported that the error occurs late in the process.  I've never seen that error message before, and it's odd: `ChemoSpec` doesn't use S4 classes (it uses S3) and the string "nir" does not appear in `ChemoSpec` code except for in a URL.  So I'm not sure to be honest.   Possibly some other package has changed its interface in a way that hasn't been detected yet.

Are you up to date with R (should be 3.5, recently released)?  And update all packages via `update.packages(ask = FALSE)` to be sure.  Then re-try please.

If freshening your installation doesn't fix it, can you post the results of `sessionInfo()` here and if possible e-mail me a few of the files you are trying to import (send to hanson@depauw.edu)?  I will keep your files private and delete them when we fix the problem.

Sorry I don't have a more definitive answer.

**Comment by spriour** [comment]
Hi Bryan,

Thanks a lot for you quick answer!
I have updated R, which was still version 3.4.3. Sorry it tooks me so long to answer, I had to deal with other issues on my computer...
Unfortunately I still get the same error.

Here is the result from sessionInfo() : 

> > sessionInfo()
> R version 3.5.0 (2018-04-23)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows >= 8 x64 (build 9200)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=English_New Zealand.1252  LC_CTYPE=English_New Zealand.1252    LC_MONETARY=English_New Zealand.1252
> [4] LC_NUMERIC=C                         LC_TIME=English_New Zealand.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] R.utils_2.6.0     R.oo_1.22.0       R.methodsS3_1.7.1 spectacles_0.5-0  pls_2.6-0         gtools_3.5.0     
> [7] ChemoSpec_4.4.97 
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_0.12.16     magrittr_1.5     splines_3.5.0    MASS_7.3-49      munsell_0.4.3    lattice_0.20-35  colorspace_1.3-2
>  [8] BiasedUrn_1.07   rlang_0.2.0      stringr_1.3.1    epiR_0.9-96      plyr_1.8.4       tools_3.5.0      grid_3.5.0      
> [15] baseline_1.2-1   gtable_0.2.0     survival_2.41-3  lazyeval_0.2.1   tibble_1.4.2     Matrix_1.2-14    reshape2_1.4.3  
> [22] ggplot2_2.2.1    signal_0.7-6     stringi_1.2.2    compiler_3.5.0   pillar_1.2.2     scales_0.5.0     SparseM_1.77  

I will send you some files now.

Thanks again!

**Comment by bryanhanson** [comment]
Sarah, the particular sample files you sent me work fine for me.  One possibility is an interference from another package -- your `sessionInfo` has quite a few things in the namespace.  Try starting R and then don't do anything else but the script that you tried for `ChemoSpec`, so your session is clean (unless, do you have a .Rprofile loading some packages automatically?  Disable that if you can.).  If you still have the problem, try it from your end with just the 7 files you sent.  Maybe there is something about one or a few files in particular, though it's hard to imagine what that would be.  Here's my `sessionInfo`:

```> sessionInfo()
R Under development (unstable) (2018-04-05 r74542)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.4

Matrix products: default
BLAS: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils    
[5] datasets  methods   base     

other attached packages:
[1] ChemoSpec_4.4.97

loaded via a namespace (and not attached):
[1] compiler_3.6.0    plyr_1.8.4       
[3] tools_3.6.0       Rcpp_0.12.16     
[5] R.methodsS3_1.7.1 grid_3.6.0       
[7] R.utils_2.6.0     R.oo_1.22.0      
```

**Comment by spriour** [comment]
As simple as that!It worked!!
So there is definitely an issue with one of the package I was loading earlier, bizarre...
But it works, so all good! 
Thanks a lot!

**Comment by bryanhanson** [comment]
All good then, just let me know any additional questions!
