### ISSUE TITLE
Problem in importing csv files in Chemospec

### ISSUE THREAD

**Issue by armak1983-2018** [bryanhanson/ChemoSpec#21]
When importing my csv files, I use the following arguments and I always get an error (even I have checked my csv files, they all have the same numbers of frequency)

ssp <- files2SpectraObject(gr.crit = c("E","F"),gr.cols = c("auto"),
                           freq.unit = "cm", int.unit = "abs", descrip = "SYD vs SYD_ACT",
                           out.file = "mydata", header= TRUE,
                           sep = ",", dec = ".", debug = TRUE, fileExt = ".csv")

Error message from R: unused arguments (gr.cols = c("auto"), out.file = "mydata")

There was a problem importing your files!

Are you importing csv or similar files?
Did you get a message such as 'undefined columns selected'?
You probably need to specify sep, header and dec values
Please read ?files2SpectraObject for details

For any trouble importing files set debug = TRUE

**Comment by bryanhanson** [comment]
Yes, unfortunately that's a bug I missed during some recent "improvements".  Also noted in #20. It is fixed in the most recent devel version.  Please install the devel versions as follows and please do let me know that it works for you:
```
install.packages("devtools")
library("devtools")
install_github(repo = "bryanhanson/ChemoSpec@devel")
install_github(repo = "bryanhanson/ChemoSpecUtils@devel")
```

**Comment by armak1983-2018** [comment]
Yes, it works ... thanks 

However, when I proceeded with the analysis, I have got the following message:

> class <- c_pcaSpectra(ssp5, choice = "noscale")
> plotScores(ssp5,class, main = myt, pcs = c(1,2), ellipse = "rob", tol = 0.01)
Error in (function (spectra, so, pcs = c(1, 2), ellipse = "none", tol = "none",  : 
  Your score object has the wrong class! Double check that the Spectra object is the 1st argument and the score object is the 2nd argument.

I got the same message with SrE.IR data. 
The message didn't appear with "autoscale" or "Paretp"....

**Comment by bryanhanson** [comment]
Hmm... Try calling the results of your pca calculation something other than "class".  "class" is the name of an existing function, R might be getting confused when you call  `plotScores`.

**Comment by armak1983-2018** [comment]
yes ... it works ... thanks for your prompt answers

**Comment by bryanhanson** [comment]
Great!
