### ISSUE TITLE
files2SpectraObject: Error message from R

### ISSUE THREAD

**Issue by benerzzz** [bryanhanson/ChemoSpec#23]
Hi Bryan,

I'm trying to upload a large number of spectra (.dx format) using files2SpectraObject and about half way through processing I get:

"Error message from R: number of items to replace is not a multiple of replacement length"

I think it has something to do with the NPOINTS (number of data points) in that some differ slightly.

Any thoughts on this issue?

**Comment by bryanhanson** [comment]
If you have spectra with differing number of data points, yes, the import process will break in much the manner you observed, so I think your diagnosis is correct.  To verify, try importing just the spectra with the same NPOINTS -- probably break things into two directories.

**Comment by benerzzz** [comment]
Separating the files worked, although a bit of a tedious process.

**Comment by bryanhanson** [comment]
So I'd guess you now have two different `Spectra` objects.  If you want more tedium, you could pad the shorter one and combine them.  Not sure of your actual need though.

**Comment by benerzzz** [comment]
Thanks for the quick response! I was able to convert my files into a csv and used the matrix2spectra function to import the files. There was a lot of manipulation in the csv files to get this to work though.

**Comment by bryanhanson** [comment]
OK, sounds like you are moving forward so I will close.
