### ISSUE TITLE
Un-split input for hypTestScores

### ISSUE THREAD

**Issue by ctr26** [bryanhanson/ChemoSpec#25]
```
data(metMUD2)
pca <- c_pcaSpectra(metMUD2)
hypTestScores(metMUD2, pca, fac = levels(metMUD2$groups))
hypTestScores(metMUD2, pca, fac = unique(metMUD2$groups))
hypTestScores(metMUD2, pca, fac = metMUD2$groups)

```
All of these do not work.

> A Spectra object contains group information stored in its spectra$groups element, but you can also use splitSpectraGroups to generate additional groups/factors that might be more useful than the original.

I don't understand why passing the levels of the data doesn't work. Using split 

Any advice welcome,

Craig

**Comment by bryanhanson** [comment]
Thank you Craig, I'll have an answer to you no later than tomorrow.

**Comment by ctr26** [comment]
Thanks for your speedy response.

When I use summary.aov on this result I get a table with a single row for "groups", but I was hoping this function would provide a table with rows for each unique label WITHIN groups. Similiar to the group example that gets fed into the manova you provide, just without grouping the four variables into two sets of two.

I tried modifying your example so it split the spectra into all possible groups, but to no avail.

I hooe I'm making sense.



Best

Craig

**Comment by bryanhanson** [comment]
The single row represents a single factor/treatment level, even though it has 4 levels.   When you split it, you have two factors/treatments, each with two levels, so you get a larger summary table (one row for each factor, plus the interaction term) -- I think I'm summarizing what you already know/discovered. 

[...goes off to experiment...]

I'm not sure if you can get a test of significance for each of the 4 levels within `groups` by themselves -- there has to an alternative to each state for comparison.  However, let's see if this is what you are thinking about:

```
res <- hypTestScores(metMUD2, pca, fac = "groups", pcs = 1) # note only 1 PC chosen
res2 <- TukeyHSD(res)
res2
plot(res2)
```
The problem with `TukeyHSD` is that it only allows 1 response term, so you can use `pcs = 1:3` (and we know from `summary.aov(res)` on the original example that both PC1 and PC2 are significant, so we can't legitimately look at them in isolation.

So far I cannot find a manova compatible version of `TukeyHSD`; it may not be possible.

Is the `TukeyHSD` approach what you are thinking about?

**Comment by ctr26** [comment]
Tukeyhsd is definitely the way I want to be going.

To emulate that functionality would manually grouping all pairwise combinations work?
