### ISSUE TITLE
Support for converting data.frame to class Spectra

### ISSUE THREAD

**Issue by abfleishman** [bryanhanson/ChemoSpec#27]
I have a bunch of data already in R in a tidy dataframe.  I am interested in converting it to the Spectra class to use some of the cool methods/functions you have created.  I have frequency, intensity and sample ID (group) columns.  a function that reads a DF and makes spectra would be really useful I think.

**Comment by bryanhanson** [comment]
Hi Abram.  Thanks for your inquiry.  By far the fastest approach would be to write that data frame to a csv file with frequencies in the first column, sample names in the first row, sample intensities in the corresponding columns (and no row numbers; use `write.table` or `write.csv`).  If you have that, then you can read it in using `matrix2SpectraObject` and you'll be all set.

As far as reading the data frame directly, that's not currently possible. It's been discussed and explored a bit, but there are just too many possible combinations to make a single function that can deal with them.

**Comment by abfleishman** [comment]
Thanks for your thoughts!  We want to use your package to do baseline correct (and maybe other things) for ~1700 FT-IR spectra measurements and we were hoping not to make a bunch of new files to keep track of.  I think I have hacked the `matrix2SpectraObject` function enough for my use case but it is a bit messy. I understand that there are too many possible combinations for a single function.  Thanks for your excellent package!

**Comment by bryanhanson** [comment]
Alright, just let me know if you need anything further.  Another option for you, if the data frames are named consistently, is to write a loop to write the csv's.  But sounds like you have it handled.
