### ISSUE TITLE
Problem with clupaSpectra

### ISSUE THREAD

**Issue by felipe-mansoldo** [bryanhanson/ChemoSpec#28]
Hello,

If you perform an operation to remove frequencies and then try to use the clupaSpectra command it will give an error:

Error in mySpec [startR: endR]: only 0's may be mixed with negative subscripts

However, the function works correctly if you do not remove frequencies.

thank you

**Comment by bryanhanson** [comment]
Hi Felipe...  I think that is to be expected given how `clupaSpectra` works (via the `speaq` package): there has to be a continuous frequency axis w/o gaps.  Try aligning first, then removing frequencies.  Let me know how it goes.

**Comment by felipe-mansoldo** [comment]
Ok, it works!
thank you

**Comment by bryanhanson** [comment]
Great, thanks for letting me know.
