### ISSUE TITLE
Importing Data matrix2SpectraObject function

### ISSUE THREAD

**Issue by Catrin-Landseer** [bryanhanson/ChemoSpec#30]
Hello,

I am using the ChemoSpec package to analyse NIR spectroscopy data. I have a file with column 1 being the wavelength, and the following columns as sample intensities. When applying the matrix2SpectraObject function I get the error message "line 1 did not have 17 elements". I understand this is an inputting error but was wondering whether you'd have any suggestions to resolve this? 

Many thanks.

**Comment by bryanhanson** [comment]
Hello!  If you can share the file please e-mail as an attachment to hanson@depauw.edu.  If you cannot share, or prefer to troubleshoot yourself, make sure you specified values for `dec` and `sep` if they are not the same as the defaults for `read.table`.  `header = TRUE` will be set automatically for you.  Another possible issue is the sample names in the header row.  `R` does not like to see anything that looks like math in the names, so no +, -, *, / Let me know how it goes!

**Comment by Catrin-Landseer** [comment]
Thank you so much, I have emailed you with the data file.

**Comment by bryanhanson** [comment]
Problem fixed offline.
