### ISSUE TITLE
chkGrafOpt needs unit tests

### ISSUE THREAD

**Issue by bryanhanson** [bryanhanson/ChemoSpec#34]
`chkGrafOpt` needs unit tests.  `ChemoSpec` uses `tinytest` and the test files go into `ChemoSpec/inst/tinytest`.

Please do this work on a branch `gsoc1-issue-X` where X is the issue number, which will eventually merge into `gsoc1`.

**Comment by bryanhanson** [comment]
Also, as part of this issue, would you also rename `chkGrafOpt` to `chkGraphicsOpt`?  Better to be clearer and easier to change now.  Thanks.

**Comment by Tejasvigupta** [comment]
okay. I will first merge the `gsoc1-issue-34` branch with my  `gsoc1` branch , rename the `chkGrafOpt` and then submit the pull request for `gsoc1` branch.

**Comment by bryanhanson** [comment]
Sounds good.

**Comment by bryanhanson** [comment]
Completed with https://github.com/bryanhanson/ChemoSpec/commit/ddf467b7bfbd4e924ea121f708fd976ff8e14643
