### ISSUE TITLE
normSpectra for body fluids

### ISSUE THREAD

**Issue by IgnacioPachon** [bryanhanson/ChemoSpec#6]
Hello. I hope this is the right way to ask you for help. If not, please tell me and I will do my best to solve it. Thank you.

The issue I'm having consists in Normalization of an IR Spectroscopy Spectra object of body fluids for forensic purposes. As I read in the manual for ChemoSpec, "Usually one normalizes data in which the sample preparation procedure may lead to differences in concentration, such as body fluids that might have been diluted during handling, or that vary due to the physiological state of the organism studied". Well, that's my case right now. Although there are three methods for doing this with the function "normSpectra" (Range, TotInt, and PQN), I haven't found them useful for my needs.

What I actually need is to get the intensities scaled between 0 and 1 (y unit is Log 1/R), so that the concentration of the fluid doesn't affect the intenstity of the whole spectra matrix. Is there any other way to get this done keeping the "Spectra" class of the object?

I am doing it this way as a kind of validation for other person's research. This person used The Unscrambler X 10.1 (Camo) software and normalized the spectra the way I mentioned. My point is getting to the same results with R software, so I need to do the most similar pre-treatment as possible.

I would appreciate any help. Thank you very much.

P.D. Thank you for the package, it is being highly useful, and I hope it becomes the ultimate tool for Spectra analysis.

**Comment by bryanhanson** [comment]
Hi Ignacio.  You should probably be using the PQN normalization method.  But if you want the largest peak in the entire data set to be scaled to 1.0 and the minimum value (which will be some noise peak) to be 0.0, I can write you a little function to do that.  That way of scaling is probably not a great choice, but I understand you are trying to parallel what was done with Unscrambler (perhaps double check their documentation that the tallest peak was set to 1.0 and not the total integration of the entire spectrum was set to 1.0).  Contact me at hanson@depauw.edu and we can continue the correspondence that way.

**Comment by IgnacioPachon** [comment]
Hey Bryan!!


I hope you are doing great! I don't know if you remember me: you helped me out with my degree project, which consisted in the analysis of spectra from body fluids. First I want to thank you again and forever for your help. Since the past year I failed one last subject (Plant Physiology), I haven't been able to defend my project. Well, I have just passed that subject and I'm getting ready to defend the project finally. Now here's the problem: since I run the script in the past, some things have changed (not a big deal, it's almost corrected) but there is one issue in my script.


> plotScoresRGL(NSBRanged, PCA_NSBR,leg.pos = "A",t.pos = "B")
Error in loadNamespace(name) : there is no package called ‘rgl’

?plotScoresRGL

Found out that the package rgl isn't available anymore!!

A priori this is not a great trouble for me because I got my captures already, but I just wanted to let you know that your function plotScoresRGL isn't working anymore.

Also I wanted to thank you for including those functions for normalization and mentioning me for suggestion! You are great!

I will let you know the score when I finally defend the project so that you can be proud of me for the use I gave to your creation!


Best wishes, friend.

Nacho Pachón Jiménez
