### ISSUE TITLE
plotScores, ggplot2 mode needs different xlab, ylab

### ISSUE THREAD

**Issue by bryanhanson** [bryanhanson/ChemoSpec#68]
Currently they just say e.g. "PC1" but they should be "PC1 score (72%)".

**Comment by Tejasvigupta** [comment]
Solved this issue in ChemoSpecUtils `plotScores` function. [https://github.com/bryanhanson/ChemoSpecUtils/pull/9](url)

**Comment by bryanhanson** [comment]
Thank you!
