### ISSUE TITLE
ggplot2 mode needs dedicated .ggAddLegend function

### ISSUE THREAD

**Issue by bryanhanson** [bryanhanson/ChemoSpec#69]
In the course of testing plots, I discovered that legends drawn by `plotSpectra` and `.scorePlot` don't accept the same inputs (in `ggplot2` mode) for `leg.loc`.

Both functions uses `npc` type positioning and `grobTree`.  But `.scorePlot` accepts strings like "topright", but it doesn't accept `list(x = , y = )` like `plotSpectra` does.

So what we need is a dedicated function, let's call it `.ggAddLegend`, that accepts any input, e.g, "none", "topright",  etc and `list(x = , y = )`.  This requires removing the code from each function and blending it in the new function.

Also, the documentation is different, they need to be blended as well.

`leg.loc` also appears in `hcaSpectra` and `hcaScores` which are not on the GSOC 2021 plan, but they will get `ggplot2` versions soon, so having `.ggLegend` will be used there too.

**Comment by Tejasvigupta** [comment]
Solved this issue in `ChemoSpecUtils` package. [https://github.com/bryanhanson/ChemoSpecUtils/pull/9](url)

**Comment by bryanhanson** [comment]
Alright, please bear with me here. `.prepLegendCoords` solves a good portion of the problem, but I still think we need a `.ggAddLegend` function.  It's a little unconventional, but I'm attaching a photo of some notes I made about what it would look like.  Such a function could be used immediately in `plotSpectra` too, not to mention the other functions I noted above (immediately because if you look there, it's the same code minus the `use.sym` feature).

![2C1215FC-6A4C-4EC7-ACE9-12926ED3CC5D_1_105_c](https://user-images.githubusercontent.com/140350/128655614-acbc51d9-d96f-4830-ab39-7c3ff15a56ca.jpeg)

**Comment by bryanhanson** [comment]
Only remaining task is to use `.ggAddLegend` in `plotSpectra` `ggplot2` mode, and `.prepLegendCoords` in `base` mode (2 lines right above `.addLegend`).

**Comment by Tejasvigupta** [comment]
This issue has been solved in #75 and hence it can be closed.
