### ISSUE TITLE
Need to look at the example plots in aovPCAscores 

### ISSUE THREAD

**Issue by Tejasvigupta** [bryanhanson/ChemoSpec#77]
The example plots for `apca2` and `apca3` shown [here](https://bryanhanson.github.io/ChemoSpec/reference/aov_pcaSpectra.html) are different from the expected plots.

**Comment by Tejasvigupta** [comment]
![aov_pcaSpectra-2](https://user-images.githubusercontent.com/63544290/131254657-c9a0c73a-3fcf-45d2-85fd-a6a9380abc19.jpg) <br>

Above is the plot that I am suppose to get for `apca2` from the example code, but when I run the code locally I am getting this plot.<br>
![aovPCA](https://user-images.githubusercontent.com/63544290/131254449-7a454cc8-c00b-4d59-827f-4a36e7fa8e1c.jpeg)
<br>
Both of these are in base graphics mode.

**Comment by bryanhanson** [comment]
Things look correct to me in both `ggplot2` and `base` modes. Perhaps you had an incompletely fixed version locally when you noticed this.  I hope. Closing for now, but will continue to watch for correctness when testing with `ChemoSpec-Plot-Combos` vignette.
