### ISSUE TITLE
plotSpectra ggplot2 graphics option: eliminate the sample label via lab.pos

### ISSUE THREAD

**Issue by bryanhanson** [bryanhanson/ChemoSpec#88]
When using `ggplot2` graphics, you cannot "delete" the sample label by setting `lab.pos` to a value outside the plotted range as you can in base graphics (because `ggplot2` will see the annotation and expand the plot limits to make it visible).

The workaround is to use `coord_cartesian` to control `xlim`.

However, we need a more general solution, perhaps setting the value to "none" (at one time I think this worked in base graphics, maybe it still does).

**Comment by gongcongcong** [comment]
ggspec <- function(spectra, offset = 0.1) {
        offset <- cumsum(rep(offset, length(spectra$names)))
        offset <- matrix(offset, nrow = length(spectra$names), ncol = length(spectra$freq))
        dat <- spectra$data + offset
        dat <- as.data.frame(dat)
        rownames(dat) <- spectra$names
        colnames(dat) <- spectra$freq
        dat <- setDT(dat, keep.rownames = TRUE)
        dat <- melt(dat, id.var = "rn")
        dat[, g := rn]
        dat[, variable := as.numeric(variable |> as.character())]
        ggplot(dat, aes(variable, value)) +
                geom_line(aes(group = rn, color = g)) +
                ggsci::scale_color_lancet() +
                scale_x_reverse(breaks = seq(min(spectra$freq)-1, max(spectra$freq), by = 400)) +
                theme_classic() +
                labs( x = "Wavenumber (cm-1)", y = "Absorbance (a.u.)", color = "")
}
ggspec(spectra) #ggspec(spectra) + guides(color = "none")

**Comment by bryanhanson** [comment]
Thank you, but we'll make a modification to the existing functions to handle the label position. I like your use of `data.table`, thinking of using that as an alternative to some retired packages.

**Comment by bryanhanson** [comment]
Implemented in https://github.com/bryanhanson/ChemoSpec/commit/648576c3ce3afef40f90b3aca3b5bdf83f3803da (likely release to CRAN in January, waiting other changes).
