### ISSUE TITLE
importing csv/excel files

### ISSUE THREAD

**Issue by emudge** [bryanhanson/ChemoSpec#9]
Everytime I try to import a matrix of batch of files using matrix2SpectraObject or files2SpectraObject I get the same error messages:
In groupNcolor(spectra, gr.crit, gr.cols) :
  There was no match for gr.crit value wineA among the file names
In groupNcolor(spectra, gr.crit, gr.cols) :
  There was no match for gr.crit value wineB among the file names
I have headers in my files that are wineA_1 to 17, etc. I have not yet been able to load any spectra using these commands.

**Comment by bryanhanson** [comment]
Can you send me (hanson@depauw.edu <mailto:hanson@depauw.edu>, or attach to Github issue but will be public) the file that is giving you trouble?

Bryan

**Comment by bryanhanson** [comment]
You need to tell R/ChemoSpec what separator the file is using:

```
tst <- matrix2SpectraObject(in.file = "matrixdata.csv", gr.crit = c('high', 'med', 'low'), sep = ",")
> sumSpectra(tst)
No gaps were found by check4Gaps
No plot will be made

 no description provided 

	There are 36 spectra in this set.
	The y-axis unit is no intensity unit provided.

	The frequency scale runs from 0 to 179.96 no frequency unit provided
	There are 17997 frequency (x-axis) data points.
	The frequency resolution is 0.01 no frequency unit provided/point.


	The spectra are divided into 3 groups: 

  group no.   color symbol alt.sym
1  high   8 #E41A1C      1       a
2   low   4 #4DAF4A      3       c
3   med  24 #377EB8      2       b

*** Note: this data is an S3 object of class 'Spectra'
```

In general, R will need to know the separator and decimal marker in use, the options are in `?read.table`.

The 2nd file you sent should work the same way, but I noticed that the file names in the header row were simply 1, 2, 3... which is hard to encode into anything useful (but you could do it by making your `gr.crit` argument `"[[:digit;]]+"` which is grep-speak for one or more digits). 

Let me know if you have any other issues or if this doesn't get you working!  Bryan

**Comment by bryanhanson** [comment]
Super! And never hesitate to ask questions, I can usually answer w/i a few hours.
