### ISSUE TITLE
plotScores_ sizes

### ISSUE THREAD

**Issue by SimoneLupini** [bryanhanson/ChemoSpec#90]
Hello, 
I'm having some issues trying to increase the font and the dot sizes, I tried using the line that I usually use on ggplot but apparently doesn't work.
I'm working with FTIR spectra and the most updated version of Chemospec
![image](https://user-images.githubusercontent.com/35562712/155854561-ef44e403-4f7e-443f-8ffb-dbed9945782d.png)

thanks

**Comment by bryanhanson** [comment]
Take a look at `str(p2)` that seems to be where the text elements of the plot are stored.  This may be helpful in figuring out what to change https://henrywang.nl/ggplot2-theme-elements-demonstration/

**Comment by bryanhanson** [comment]
Were you able to get things working the way you wanted?
