### ISSUE TITLE
readJDX format X Y...Y

### ISSUE THREAD

**Issue by TDMuellers** [bryanhanson/ChemoSpec#91]
I have a number of spectra in JDX files with format: XYYYYY. Each Y value, after the first on each line, corresponds to the next frequency on the X axis. Sample below:

##XYDATA=(X++(Y..Y))
657.000000 0.8927 0.8947 0.8886 0.8868 0.8843
662.000000 0.8816 0.8780 0.8737 0.8676 0.8612

readJDX is able to read these, but I am getting the error message, "Error message from R: Couldn't find any variable lists.  Supported formats are: XYY, XRR, XII, NMR_2D, LC_MS, XYXY, XYXY" when I try importing using files2SpectraObject. 

Is there a possible workaround or a way to specify the import format?

**Comment by bryanhanson** [comment]
OK great, good work.  I had replied earlier today but I don't see it here, oddly. Let me know any further questions/issues of course, there are some weird things in some files!

**Comment by TDMuellers** [comment]
Hi Bryan,

Thanks for following up on this. I found a suitable workaround. Thank you.

Best regards,

Tobias

From: Bryan Hanson ***@***.***>
Date: Tuesday, October 11, 2022 at 4:12 AM
To: bryanhanson/ChemoSpec ***@***.***>
Cc: Muellers, Tobias ***@***.***>, State change ***@***.***>
Subject: Re: [bryanhanson/ChemoSpec] readJDX format X Y...Y (Issue #91)
Can you attach a couple of sample files or send to my email and I'll take a look! Bryan
