### ISSUE TITLE
Is there a way to add Spectra objects after imported, smoothed, and baseline corrected each of their own?

### ISSUE THREAD

**Issue by arduh** [bryanhanson/ChemoSpec#94]
Thank you sir, your package helped me a lot. 
I want to add differently preprocessed spectral data and plot them in the same graph, with same principal components.
Should I just preprocess them all together? I mean, their baselines do not match.
Thank you.

**Comment by arduh** [comment]
Also, can I access groups and single Spectra measurements inside the Spectra object? I want to remove the influence of water. Thus maybe I can subtract pure water measurements from all spectra measurements one by one, or by groups.

**Comment by arduh** [comment]
We are using FTIR, I simply subtracted the water readings from our sample in OriginLab. 
I am merely a student, I try to make a PCA graph similiar to a graph done by a data scientist in my school. If I can understand the proper steps, I will try to do PCA-HCAs in a new study of mine.

**Comment by bryanhanson** [comment]
We are all students, all the time!

For IR, subtracting water is extremely challenging, so be careful. I'm not sure what wavenumbers are of interest in your study, but ideally they are far from the water peaks so you don't need to do anything with the water peaks.

For more details on PCA, you can take a look at the examples in the `ChemoSpec` manual (`browseVignettes("ChemoSpec")`) or to really dig down, look at [LearnPCA](https://bryanhanson.github.io/LearnPCA/index.html).

**Comment by arduh** [comment]
Our samples are protein expression yeasts in aqueous suspensions. Thus, I guess I have to. But it really is challenging. I can't figure out how should I preprocess my data. 
Thank you for your answers. Loved reading your blog too, sir.
