### ISSUE TITLE
ChemoSpec seems to have a memory

### ISSUE THREAD

**Issue by ErrorCode331** [bryanhanson/ChemoSpec#95]
Here is my code to convert my files to a Spectra object.

IRdata=files2SpectraObject(
	gr.crit = c("CGPb","Chs"),
	gr.cols = c("red","blue"),
	freq.unit = "cm-1",
	int.unit = "peak intensity",
	descrip = "Glucans",
 	sep =',',
	debug = TRUE,
	out.file = "FTIR")
 
ChemoSpec refuses to convert them to a Spectra Object although they seem to load OK

The first warning is:
Warning messages:
1: In .groupNcolor(spectra, gr.crit, gr.cols, mode = "1D") :
  There was no match for gr.crit value ssChs among the file names.

? There is no value ssChs in gr,crit as the code is currently written - see above?

Its true to say I have used that value to encode a group in the past but the value does not occur anywhere in my present code and is not used in any of the file names in the working directory.

What's going on?

**Comment by bryanhanson** [comment]
That's a curious error, I agree.  If you are using the R GUI, it does have a setting to save your workspace and history when you quit a session and reload them on the next start up.  It's possible that these being loaded when you start up, and that is *somehow* contaminating your new work.  I have these "features" off for this reason. You might check those settings.

If you like you can e-mail me some files and your script and I can test in my (different, clean?) environment.  hanson@depauw.edu.

**Comment by ErrorCode331** [comment]
Seems to be something to do with my .history file. Not loading it makes the problem go away - sorry for my nuisance value!

**Comment by bryanhanson** [comment]
Great.  Hard to see sometimes exactly what's leaking into the workspace but if nuking it works, onward!
